"""Flask application entry point with APScheduler.

Generated by claude-internal tools.
"""
import os
from flask import Flask, render_template
from werkzeug.middleware.proxy_fix import ProxyFix
from apscheduler.schedulers.background import BackgroundScheduler
import config
from models.database import init_db

_scheduler = None

# URL prefix: set APPLICATION_ROOT=/cmb for sub-path deployment, default empty
URL_PREFIX = os.environ.get("URL_PREFIX", "")


def create_app():
    app = Flask(__name__, static_url_path=URL_PREFIX + "/static")
    app.config["SECRET_KEY"] = config.SECRET_KEY

    # Trust reverse proxy headers
    app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1)

    # Initialize database
    init_db()

    # Register blueprints with prefix
    from routes.dashboard import bp as dashboard_bp
    from routes.analysis import bp as analysis_bp
    from routes.data_mgmt import bp as data_mgmt_bp

    app.register_blueprint(dashboard_bp, url_prefix=URL_PREFIX)
    app.register_blueprint(analysis_bp, url_prefix=URL_PREFIX)
    app.register_blueprint(data_mgmt_bp, url_prefix=URL_PREFIX)

    # Page routes
    @app.route(URL_PREFIX + "/")
    def index():
        return render_template("dashboard.html", active_page="dashboard", prefix=URL_PREFIX)

    @app.route(URL_PREFIX + "/analysis")
    def analysis_page():
        return render_template("analysis.html", active_page="analysis", prefix=URL_PREFIX)

    @app.route(URL_PREFIX + "/data")
    def data_page():
        return render_template("data_mgmt.html", active_page="data", prefix=URL_PREFIX)

    # Start scheduler once (avoid duplicates in gunicorn preload / multi-worker)
    global _scheduler
    if _scheduler is None:
        _scheduler = _start_scheduler(app)

    return app


def _start_scheduler(app):
    """Start APScheduler for daily fetch."""
    from datetime import datetime, timedelta
    from services.pipeline import run_fetch_pipeline

    def daily_job():
        with app.app_context():
            now = datetime.now()
            yesterday = now - timedelta(days=1)
            try:
                run_fetch_pipeline(yesterday, now, fetch_type="daily")
                print(f"[Scheduler] Daily fetch completed at {now}")
            except Exception as e:
                print(f"[Scheduler] Daily fetch failed: {e}")

    scheduler = BackgroundScheduler()
    for idx, (hour, minute) in enumerate(config.DAILY_FETCH_TIMES):
        scheduler.add_job(
            daily_job,
            "cron",
            hour=hour,
            minute=minute,
            id=f"daily_fetch_{idx}",
        )
        print(f"[Scheduler] Daily fetch scheduled at {hour:02d}:{minute:02d}")
    scheduler.start()
    return scheduler


app = create_app()

if __name__ == "__main__":
    app.run(debug=config.DEBUG, port=5002, use_reloader=False)
