#!/bin/bash
# Build script — package deployment files into a tar.gz archive.
# Generated by claude-internal tools.
#
# Usage: ./build.sh
# Output: cmb-bill-tracker-YYYYMMDD.tar.gz

set -e
cd "$(dirname "$0")"

DATE=$(date +%Y%m%d)
PKG_NAME="cmb-bill-tracker-${DATE}"
DIST_DIR="/tmp/${PKG_NAME}"

echo "Packaging ${PKG_NAME}..."

# Clean
rm -rf "$DIST_DIR"
mkdir -p "$DIST_DIR"

# Copy project files
cp app.py config.py init_db.py requirements.txt restart.sh deploy.sh Dockerfile .dockerignore "$DIST_DIR/"
cp -r models services routes templates static "$DIST_DIR/"

# Ensure scripts are executable
chmod +x "$DIST_DIR/restart.sh" "$DIST_DIR/deploy.sh"

# Archive
TAR_FILE="$(pwd)/${PKG_NAME}.tar.gz"
tar -czf "$TAR_FILE" -C /tmp "$PKG_NAME"

# Clean temp
rm -rf "$DIST_DIR"

SIZE=$(du -h "$TAR_FILE" | cut -f1)
echo "Done: ${TAR_FILE} (${SIZE})"
echo ""
echo "Deploy to server:"
echo "  scp ${TAR_FILE} user@server:/opt/"
echo "  ssh user@server 'cd /opt && tar xzf ${PKG_NAME}.tar.gz && cd ${PKG_NAME} && pip install -r requirements.txt && URL_PREFIX=/cmb nohup python3 app.py > server.log 2>&1 &'"
