# Generated by claude-internal tools.
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Database — can be overridden by env var for Docker volume mount
DATABASE_PATH = os.environ.get("DATABASE_PATH", os.path.join(BASE_DIR, "cmb_bills.db"))

# IMAP settings for 163 mail
IMAP_HOST = os.environ.get("IMAP_HOST", "imap.163.com")
IMAP_PORT = int(os.environ.get("IMAP_PORT", 993))
EMAIL_ADDRESS = os.environ.get("EMAIL_ADDRESS", "zhouzhiyong93@163.com")
EMAIL_AUTH_CODE = os.environ.get("EMAIL_AUTH_CODE", "LRnHDJWR3UuhVwuJ")  # 授权码

# Flask
SECRET_KEY = os.environ.get("SECRET_KEY", "cmb-bill-tracker-secret-key")
DEBUG = os.environ.get("DEBUG", "false").lower() in ("true", "1")

# Scheduler
DAILY_FETCH_HOUR = int(os.environ.get("DAILY_FETCH_HOUR", 9))
DAILY_FETCH_MINUTE = int(os.environ.get("DAILY_FETCH_MINUTE", 0))
