#!/bin/bash
# Deploy script — build Docker image and run container.
# Generated by claude-internal tools.
#
# Usage:
#   ./deploy.sh              # build & run
#   ./deploy.sh stop         # stop container
#   ./deploy.sh logs         # view logs

set -e
IMAGE_NAME="cmb-bill-tracker"
CONTAINER_NAME="cmb-bill-tracker"
PORT=5002
DATA_DIR="$(cd "$(dirname "$0")" && pwd)/data"

case "${1:-run}" in
  stop)
    echo "Stopping $CONTAINER_NAME..."
    docker stop "$CONTAINER_NAME" 2>/dev/null && docker rm "$CONTAINER_NAME" 2>/dev/null
    echo "Stopped."
    ;;
  logs)
    docker logs -f "$CONTAINER_NAME"
    ;;
  *)
    # Stop old container if running
    docker stop "$CONTAINER_NAME" 2>/dev/null && docker rm "$CONTAINER_NAME" 2>/dev/null || true

    # Build
    echo "Building image..."
    cd "$(dirname "$0")"
    docker build -t "$IMAGE_NAME" .

    # Ensure data dir for persistent DB
    mkdir -p "$DATA_DIR"

    # Run
    echo "Starting container on port $PORT..."
    docker run -d \
      --name "$CONTAINER_NAME" \
      --restart unless-stopped \
      -p "$PORT:5002" \
      -v "$DATA_DIR:/app/data" \
      -e DATABASE_PATH=/app/data/cmb_bills.db \
      "$IMAGE_NAME"

    echo "Running at http://localhost:$PORT"
    echo "DB persisted at $DATA_DIR/cmb_bills.db"
    ;;
esac
