#!/bin/bash
# Generated by claude-internal tools.
# Restart the CMB bill tracker Flask server on port 5002.
# use command in server end: VENV_DIR=/other/path/venv URL_PREFIX=/cmb bash restart.sh

cd "$(dirname "$0")"

# Use venv Python if available
VENV_DIR="${VENV_DIR:-/home/ubuntu/tools/venv}"
if [ -d "$VENV_DIR/bin" ]; then
    export PATH="$VENV_DIR/bin:$PATH"
    echo "Using Python: $(which python3)"
fi

# Kill existing process on port 5002
PID=$(lsof -ti :5002 2>/dev/null)
if [ -n "$PID" ]; then
    echo "Stopping existing process (PID: $PID)..."
    kill "$PID" 2>/dev/null
    sleep 1
fi

echo "Starting server on port 5002..."
nohup python3 app.py > server.log 2>&1 &
echo "Server started (PID: $!), log: server.log"
