"""Analysis API routes.

Generated by claude-internal tools.
"""
from flask import Blueprint, jsonify, request
from models.database import get_db
from datetime import datetime

bp = Blueprint("analysis", __name__)


@bp.route("/api/analysis/category")
def category_analysis():
    """Category breakdown for pie chart and bar chart."""
    db = get_db()
    date_from = request.args.get("date_from", f"{datetime.now().year}-01-01")
    date_to = request.args.get("date_to", datetime.now().strftime("%Y-%m-%d"))
    card = request.args.get("card", "")

    try:
        if card:
            rows = db.execute(
                """SELECT category, COUNT(*) as count, SUM(amount) as total
                   FROM transactions
                   WHERE trans_date >= ? AND trans_date <= ? AND card_last4 = ? AND refunded = 0
                   GROUP BY category
                   ORDER BY total DESC""",
                (date_from, date_to, card),
            ).fetchall()
        else:
            rows = db.execute(
                """SELECT category, COUNT(*) as count, SUM(amount) as total
                   FROM transactions
                   WHERE trans_date >= ? AND trans_date <= ? AND refunded = 0
                   GROUP BY category
                   ORDER BY total DESC""",
                (date_from, date_to),
            ).fetchall()

        data = [
            {"category": r["category"], "count": r["count"], "total": round(r["total"], 2)}
            for r in rows
        ]

        return jsonify({"data": data})
    finally:
        db.close()


@bp.route("/api/analysis/monthly-trend")
def monthly_trend():
    """Monthly spending trend for line chart."""
    db = get_db()
    date_from = request.args.get("date_from", f"{datetime.now().year}-01-01")
    date_to = request.args.get("date_to", datetime.now().strftime("%Y-%m-%d"))

    try:
        rows = db.execute(
            """SELECT card_last4,
                      strftime('%Y-%m', trans_date) as month,
                      SUM(amount) as total,
                      COUNT(*) as count
               FROM transactions
               WHERE trans_date >= ? AND trans_date <= ? AND refunded = 0
               GROUP BY card_last4, month
               ORDER BY month""",
            (date_from, date_to),
        ).fetchall()

        # Organize by card
        trend = {}
        months_set = set()
        for r in rows:
            card = r["card_last4"]
            month = r["month"]
            months_set.add(month)
            if card not in trend:
                trend[card] = {}
            trend[card][month] = {"total": round(r["total"], 2), "count": r["count"]}

        months = sorted(months_set)

        return jsonify({"months": months, "trend": trend})
    finally:
        db.close()


@bp.route("/api/analysis/transactions")
def transaction_list():
    """Transaction list with search, filter, pagination."""
    db = get_db()
    date_from = request.args.get("date_from", f"{datetime.now().year}-01-01")
    date_to = request.args.get("date_to", datetime.now().strftime("%Y-%m-%d"))
    card = request.args.get("card", "")
    category = request.args.get("category", "")
    search = request.args.get("search", "")
    page = int(request.args.get("page", 1))
    per_page = int(request.args.get("per_page", 20))

    try:
        conditions = ["trans_date >= ?", "trans_date <= ?"]
        params = [date_from, date_to]

        if card:
            conditions.append("card_last4 = ?")
            params.append(card)
        if category:
            conditions.append("category = ?")
            params.append(category)
        if search:
            conditions.append("merchant LIKE ?")
            params.append(f"%{search}%")

        where = " AND ".join(conditions)

        # Total count (exclude refunded)
        total = db.execute(
            f"SELECT COUNT(*) as cnt FROM transactions WHERE {where} AND refunded = 0", params
        ).fetchone()["cnt"]

        # Paginated results
        offset = (page - 1) * per_page
        rows = db.execute(
            f"""SELECT id, card_last4, trans_date, post_date, amount, merchant, category, bill_type, refunded, refund_date
                FROM transactions
                WHERE {where}
                ORDER BY trans_date DESC, id DESC
                LIMIT ? OFFSET ?""",
            params + [per_page, offset],
        ).fetchall()

        data = [
            {
                "id": r["id"],
                "card_last4": r["card_last4"],
                "trans_date": r["trans_date"],
                "post_date": r["post_date"],
                "amount": r["amount"],
                "merchant": r["merchant"],
                "category": r["category"],
                "bill_type": r["bill_type"],
                "refunded": r["refunded"],
                "refund_date": r["refund_date"],
            }
            for r in rows
        ]

        return jsonify(
            {
                "data": data,
                "total": total,
                "page": page,
                "per_page": per_page,
                "total_pages": (total + per_page - 1) // per_page,
            }
        )
    finally:
        db.close()
