"""Dashboard API routes.

Generated by claude-internal tools.
"""
from flask import Blueprint, jsonify
from models.database import get_db
from datetime import datetime

bp = Blueprint("dashboard", __name__)


@bp.route("/api/dashboard")
def dashboard_data():
    """Return dashboard summary data."""
    db = get_db()
    today = datetime.now()
    year_start = f"{today.year}-01-01"
    month_start = f"{today.year}-{today.month:02d}-01"
    today_str = today.strftime("%Y-%m-%d")

    try:
        # Monthly totals by card
        monthly = db.execute(
            """SELECT card_last4,
                      COUNT(*) as count,
                      COALESCE(SUM(amount), 0) as total
               FROM transactions
               WHERE trans_date >= ? AND trans_date <= ? AND refunded = 0
               GROUP BY card_last4""",
            (month_start, today_str),
        ).fetchall()

        monthly_data = {row["card_last4"]: {"count": row["count"], "total": row["total"]} for row in monthly}
        monthly_total = sum(r["total"] for r in monthly)
        monthly_count = sum(r["count"] for r in monthly)

        # Yearly totals by card
        yearly = db.execute(
            """SELECT card_last4,
                      COUNT(*) as count,
                      COALESCE(SUM(amount), 0) as total
               FROM transactions
               WHERE trans_date >= ? AND trans_date <= ? AND refunded = 0
               GROUP BY card_last4""",
            (year_start, today_str),
        ).fetchall()

        yearly_data = {row["card_last4"]: {"count": row["count"], "total": row["total"]} for row in yearly}
        yearly_total = sum(r["total"] for r in yearly)
        yearly_count = sum(r["count"] for r in yearly)

        # Get distinct card numbers
        cards = db.execute(
            "SELECT DISTINCT card_last4 FROM transactions ORDER BY card_last4"
        ).fetchall()
        card_list = [row["card_last4"] for row in cards]

        # Recent transactions per card (last 15 each)
        recent_by_card = {}
        for card in card_list:
            rows = db.execute(
                """SELECT id, card_last4, trans_date, amount, merchant, category, refunded
                   FROM transactions
                   WHERE card_last4 = ?
                   ORDER BY trans_date DESC, id DESC
                   LIMIT 15""",
                (card,),
            ).fetchall()
            recent_by_card[card] = [
                {
                    "id": r["id"],
                    "card_last4": r["card_last4"],
                    "trans_date": r["trans_date"],
                    "amount": r["amount"],
                    "merchant": r["merchant"],
                    "category": r["category"],
                    "refunded": r["refunded"],
                }
                for r in rows
            ]

        # Top 10 spending per card (this month)
        top10_monthly = {}
        for card in card_list:
            rows = db.execute(
                """SELECT trans_date, amount, merchant, category
                   FROM transactions
                   WHERE card_last4 = ? AND trans_date >= ? AND trans_date <= ? AND refunded = 0
                   ORDER BY amount DESC
                   LIMIT 10""",
                (card, month_start, today_str),
            ).fetchall()
            top10_monthly[card] = [
                {"trans_date": r["trans_date"], "amount": r["amount"], "merchant": r["merchant"], "category": r["category"]}
                for r in rows
            ]

        # Top 10 spending per card (this year)
        top10_yearly = {}
        for card in card_list:
            rows = db.execute(
                """SELECT trans_date, amount, merchant, category
                   FROM transactions
                   WHERE card_last4 = ? AND trans_date >= ? AND trans_date <= ? AND refunded = 0
                   ORDER BY amount DESC
                   LIMIT 10""",
                (card, year_start, today_str),
            ).fetchall()
            top10_yearly[card] = [
                {"trans_date": r["trans_date"], "amount": r["amount"], "merchant": r["merchant"], "category": r["category"]}
                for r in rows
            ]

        return jsonify(
            {
                "cards": card_list,
                "monthly": {
                    "by_card": monthly_data,
                    "total": monthly_total,
                    "count": monthly_count,
                    "period": f"{today.year}年{today.month}月",
                },
                "yearly": {
                    "by_card": yearly_data,
                    "total": yearly_total,
                    "count": yearly_count,
                    "period": f"{today.year}年",
                },
                "top10_monthly": top10_monthly,
                "top10_yearly": top10_yearly,
                "recent_by_card": recent_by_card,
            }
        )
    finally:
        db.close()
