"""Data management API routes — fetch triggers, status, logs.

Generated by claude-internal tools.
"""
from flask import Blueprint, jsonify, request
from models.database import get_db
from services.pipeline import run_fetch_pipeline
from datetime import datetime, timedelta
import threading

bp = Blueprint("data_mgmt", __name__)

# Track running fetch tasks
_running_tasks = {}


def _mark_refund(db, refund_trans):
    """Find the original transaction matching this refund and mark it as refunded.

    Match by: same card, same merchant, same amount, transaction date <= refund date.
    Picks the most recent un-refunded match.
    """
    row = db.execute(
        """SELECT id FROM transactions
           WHERE card_last4 = ? AND merchant = ? AND amount = ?
                 AND refunded = 0 AND trans_date <= ?
           ORDER BY trans_date DESC
           LIMIT 1""",
        (
            refund_trans["card_last4"],
            refund_trans["merchant"],
            refund_trans["amount"],
            refund_trans["trans_date"],
        ),
    ).fetchone()

    if row:
        db.execute(
            "UPDATE transactions SET refunded = 1, refund_date = ? WHERE id = ?",
            (refund_trans["trans_date"], row["id"]),
        )
        db.commit()


def _run_fetch_in_thread(fetch_log_id, date_from, date_to, fetch_type):
    """Run fetch pipeline in a background thread."""
    try:
        run_fetch_pipeline(date_from, date_to, fetch_type)
    finally:
        _running_tasks.pop(fetch_log_id, None)


@bp.route("/api/fetch", methods=["POST"])
def trigger_fetch():
    """Trigger a fetch operation.

    JSON body:
        period: '7d', '30d', '6m', '1y', '3y', '5y', 'custom'
        date_from: (for custom) YYYY-MM-DD
        date_to: (for custom) YYYY-MM-DD
    """
    data = request.get_json() or {}
    period = data.get("period", "7d")
    now = datetime.now()

    period_map = {
        "7d": timedelta(days=7),
        "30d": timedelta(days=30),
        "6m": timedelta(days=180),
        "1y": timedelta(days=365),
        "3y": timedelta(days=365 * 3),
        "5y": timedelta(days=365 * 5),
    }

    if period == "custom":
        date_from = datetime.strptime(data["date_from"], "%Y-%m-%d")
        date_to = datetime.strptime(data["date_to"], "%Y-%m-%d")
        fetch_type = "custom"
    elif period in period_map:
        date_from = now - period_map[period]
        date_to = now
        fetch_type = f"init_{period}"
    else:
        return jsonify({"error": "Invalid period"}), 400

    # Create fetch log first
    db = get_db()
    db.execute(
        "INSERT INTO fetch_logs (fetch_type, date_from, date_to, status) VALUES (?, ?, ?, 'running')",
        (fetch_type, date_from.strftime("%Y-%m-%d"), date_to.strftime("%Y-%m-%d")),
    )
    db.commit()
    fetch_log_id = db.execute("SELECT last_insert_rowid()").fetchone()[0]
    db.close()

    # Run in background thread
    thread = threading.Thread(
        target=_run_fetch_in_background,
        args=(fetch_log_id, date_from, date_to, fetch_type),
    )
    thread.daemon = True
    thread.start()
    _running_tasks[fetch_log_id] = thread

    return jsonify({"fetch_id": fetch_log_id, "status": "running"})


def _run_fetch_in_background(fetch_log_id, date_from, date_to, fetch_type):
    """Background fetch — updates the existing fetch_log entry."""
    from services.email_fetcher import fetch_cmb_emails
    from services.bill_parser import parse_email
    from services.dedup import compute_dedup_hash, is_duplicate
    from services.category_mapper import categorize_merchant

    db = get_db()
    emails_parsed = 0
    records_created = 0

    try:
        emails = fetch_cmb_emails(date_from, date_to, fetch_log_id)

        db.execute(
            "UPDATE fetch_logs SET emails_found = ? WHERE id = ?",
            (len(emails), fetch_log_id),
        )
        db.commit()

        for email_data in emails:
            uid = email_data["uid"]

            db.execute(
                """INSERT OR IGNORE INTO email_logs (email_uid, subject, from_addr, date, parsed_status)
                   VALUES (?, ?, ?, ?, 'pending')""",
                (uid, email_data["subject"], email_data["from_addr"], email_data["date"]),
            )
            db.commit()

            try:
                result = parse_email(email_data)
                bill_type = result["bill_type"]
                transactions = result["transactions"]

                if bill_type == "unknown" or not transactions:
                    db.execute(
                        "UPDATE email_logs SET parsed_status = 'skipped', bill_type = ? WHERE email_uid = ?",
                        (bill_type, uid),
                    )
                    db.commit()
                    continue

                email_records = 0
                for trans in transactions:
                    # Handle refunds: find and mark original transaction
                    if trans.get("is_refund"):
                        _mark_refund(db, trans)
                        continue

                    dedup_hash = compute_dedup_hash(
                        trans["card_last4"],
                        trans["trans_date"],
                        trans["amount"],
                        trans["merchant"],
                    )

                    if is_duplicate(db, dedup_hash):
                        continue

                    category = categorize_merchant(trans["merchant"])

                    db.execute(
                        """INSERT INTO transactions
                           (card_last4, trans_date, post_date, amount, currency, merchant,
                            category, bill_type, dedup_hash, email_uid)
                           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                        (
                            trans["card_last4"],
                            trans["trans_date"],
                            trans.get("post_date", trans["trans_date"]),
                            trans["amount"],
                            trans.get("currency", "CNY"),
                            trans["merchant"],
                            category,
                            trans["bill_type"],
                            dedup_hash,
                            uid,
                        ),
                    )
                    email_records += 1
                    records_created += 1

                db.execute(
                    """UPDATE email_logs
                       SET parsed_status = 'success', bill_type = ?, records_count = ?
                       WHERE email_uid = ?""",
                    (bill_type, email_records, uid),
                )
                db.commit()
                emails_parsed += 1

            except Exception as e:
                db.execute(
                    "UPDATE email_logs SET parsed_status = 'failed', error_message = ? WHERE email_uid = ?",
                    (str(e), uid),
                )
                db.commit()

        db.execute(
            """UPDATE fetch_logs
               SET status = 'completed', emails_parsed = ?, records_created = ?,
                   completed_at = datetime('now', 'localtime')
               WHERE id = ?""",
            (emails_parsed, records_created, fetch_log_id),
        )
        db.commit()

    except Exception as e:
        db.execute(
            """UPDATE fetch_logs
               SET status = 'failed', error_message = ?,
                   completed_at = datetime('now', 'localtime')
               WHERE id = ?""",
            (str(e), fetch_log_id),
        )
        db.commit()
    finally:
        db.close()
        _running_tasks.pop(fetch_log_id, None)


@bp.route("/api/fetch/<int:fetch_id>/status")
def fetch_status(fetch_id):
    """Get status of a fetch operation."""
    db = get_db()
    try:
        row = db.execute(
            """SELECT id, fetch_type, date_from, date_to, status,
                      emails_found, emails_parsed, records_created,
                      error_message, started_at, completed_at
               FROM fetch_logs WHERE id = ?""",
            (fetch_id,),
        ).fetchone()

        if not row:
            return jsonify({"error": "Not found"}), 404

        return jsonify(
            {
                "id": row["id"],
                "fetch_type": row["fetch_type"],
                "date_from": row["date_from"],
                "date_to": row["date_to"],
                "status": row["status"],
                "emails_found": row["emails_found"],
                "emails_parsed": row["emails_parsed"],
                "records_created": row["records_created"],
                "error_message": row["error_message"],
                "started_at": row["started_at"],
                "completed_at": row["completed_at"],
            }
        )
    finally:
        db.close()


@bp.route("/api/fetch-logs")
def fetch_logs():
    """Get fetch history."""
    db = get_db()
    try:
        rows = db.execute(
            """SELECT id, fetch_type, date_from, date_to, status,
                      emails_found, emails_parsed, records_created,
                      error_message, started_at, completed_at
               FROM fetch_logs
               ORDER BY id DESC
               LIMIT 50"""
        ).fetchall()

        data = [
            {
                "id": r["id"],
                "fetch_type": r["fetch_type"],
                "date_from": r["date_from"],
                "date_to": r["date_to"],
                "status": r["status"],
                "emails_found": r["emails_found"],
                "emails_parsed": r["emails_parsed"],
                "records_created": r["records_created"],
                "error_message": r["error_message"],
                "started_at": r["started_at"],
                "completed_at": r["completed_at"],
            }
            for r in rows
        ]

        return jsonify({"data": data})
    finally:
        db.close()


@bp.route("/api/cron/daily-fetch", methods=["POST"])
def daily_fetch():
    """Trigger daily fetch (yesterday's emails)."""
    now = datetime.now()
    yesterday = now - timedelta(days=1)

    db = get_db()
    db.execute(
        "INSERT INTO fetch_logs (fetch_type, date_from, date_to, status) VALUES (?, ?, ?, 'running')",
        ("daily", yesterday.strftime("%Y-%m-%d"), now.strftime("%Y-%m-%d")),
    )
    db.commit()
    fetch_log_id = db.execute("SELECT last_insert_rowid()").fetchone()[0]
    db.close()

    thread = threading.Thread(
        target=_run_fetch_in_background,
        args=(fetch_log_id, yesterday, now, "daily"),
    )
    thread.daemon = True
    thread.start()
    _running_tasks[fetch_log_id] = thread

    return jsonify({"fetch_id": fetch_log_id, "status": "running"})


@bp.route("/api/stats")
def data_stats():
    """Get overall data statistics."""
    db = get_db()
    try:
        total_trans = db.execute("SELECT COUNT(*) as cnt FROM transactions").fetchone()["cnt"]
        total_amount = db.execute(
            "SELECT COALESCE(SUM(amount), 0) as total FROM transactions"
        ).fetchone()["total"]

        cards = db.execute(
            """SELECT card_last4, COUNT(*) as cnt, SUM(amount) as total
               FROM transactions GROUP BY card_last4"""
        ).fetchall()

        date_range = db.execute(
            "SELECT MIN(trans_date) as min_date, MAX(trans_date) as max_date FROM transactions"
        ).fetchone()

        email_stats = db.execute(
            """SELECT parsed_status, COUNT(*) as cnt
               FROM email_logs GROUP BY parsed_status"""
        ).fetchall()

        return jsonify(
            {
                "total_transactions": total_trans,
                "total_amount": round(total_amount, 2),
                "cards": [
                    {"card_last4": c["card_last4"], "count": c["cnt"], "total": round(c["total"], 2)}
                    for c in cards
                ],
                "date_range": {
                    "from": date_range["min_date"],
                    "to": date_range["max_date"],
                }
                if date_range["min_date"]
                else None,
                "email_stats": {r["parsed_status"]: r["cnt"] for r in email_stats},
            }
        )
    finally:
        db.close()


@bp.route("/api/categories")
def list_categories():
    """Get all distinct categories currently in use."""
    db = get_db()
    try:
        rows = db.execute(
            "SELECT DISTINCT category FROM transactions ORDER BY category"
        ).fetchall()
        rule_rows = db.execute(
            "SELECT DISTINCT category FROM category_rules ORDER BY category"
        ).fetchall()
        cats = sorted(set([r["category"] for r in rows] + [r["category"] for r in rule_rows]))
        return jsonify({"categories": cats})
    finally:
        db.close()


@bp.route("/api/uncategorized")
def uncategorized_transactions():
    """Get transactions with category '其他'."""
    db = get_db()
    try:
        rows = db.execute(
            """SELECT id, card_last4, trans_date, amount, merchant, category
               FROM transactions
               WHERE category = '其他' AND refunded = 0
               ORDER BY trans_date DESC"""
        ).fetchall()
        data = [
            {
                "id": r["id"],
                "card_last4": r["card_last4"],
                "trans_date": r["trans_date"],
                "amount": r["amount"],
                "merchant": r["merchant"],
                "category": r["category"],
            }
            for r in rows
        ]
        return jsonify({"data": data, "total": len(data)})
    finally:
        db.close()


@bp.route("/api/transactions/<int:trans_id>/category", methods=["PUT"])
def update_transaction_category(trans_id):
    """Update category for a single transaction."""
    data = request.get_json() or {}
    category = data.get("category", "").strip()
    if not category:
        return jsonify({"error": "category is required"}), 400

    db = get_db()
    try:
        db.execute(
            "UPDATE transactions SET category = ? WHERE id = ?",
            (category, trans_id),
        )
        db.commit()
        return jsonify({"ok": True})
    finally:
        db.close()


@bp.route("/api/merchants")
def merchant_list():
    """Get all distinct merchants with frequency and current category."""
    db = get_db()
    try:
        rows = db.execute(
            """SELECT merchant, category, COUNT(*) as cnt, SUM(amount) as total
               FROM transactions
               WHERE refunded = 0
               GROUP BY merchant
               ORDER BY cnt DESC"""
        ).fetchall()
        data = [
            {
                "merchant": r["merchant"],
                "category": r["category"],
                "count": r["cnt"],
                "total": round(r["total"], 2),
            }
            for r in rows
        ]
        return jsonify({"data": data, "total": len(data)})
    finally:
        db.close()


@bp.route("/api/merchants/category", methods=["PUT"])
def update_merchant_category():
    """Batch update category for all transactions of a merchant.

    Also adds/updates a category_rule for future auto-categorization.
    JSON body: { merchant: "xxx", category: "xxx" }
    """
    data = request.get_json() or {}
    merchant = data.get("merchant", "").strip()
    category = data.get("category", "").strip()
    if not merchant or not category:
        return jsonify({"error": "merchant and category are required"}), 400

    db = get_db()
    try:
        result = db.execute(
            "UPDATE transactions SET category = ? WHERE merchant = ?",
            (category, merchant),
        )
        updated = result.rowcount
        db.commit()

        # Upsert category rule
        existing = db.execute(
            "SELECT id FROM category_rules WHERE pattern = ?", (merchant,)
        ).fetchone()
        if existing:
            db.execute(
                "UPDATE category_rules SET category = ? WHERE id = ?",
                (category, existing["id"]),
            )
        else:
            db.execute(
                "INSERT INTO category_rules (pattern, category, priority) VALUES (?, ?, 20)",
                (merchant, category),
            )
        db.commit()

        return jsonify({"ok": True, "updated": updated})
    finally:
        db.close()
