"""CMB bill email parser — handles daily transaction alerts and monthly statements.

Generated by claude-internal tools.

CMB "每日信用管家" email format (observed):
  - Date line (in a td): "2026/03/15\xa0您的消费明细如下："
  - Transaction lines (in td cells):
    "HH:MM:SSCNY\xa0AMOUNT尾号XXXX\xa0消费/退货\xa0MERCHANT"
    e.g. "17:20:54CNY\xa014.00尾号6212\xa0消费\xa0支付宝-上海拉扎斯信息科技有限公司"
"""
import re
from bs4 import BeautifulSoup
from datetime import datetime


# Regex for the transaction line in "每日信用管家"
# Matches: HH:MM:SS CNY AMOUNT 尾号XXXX 消费/退货 MERCHANT
_TRANS_RE = re.compile(
    r"(\d{2}:\d{2}:\d{2})"       # time
    r"CNY[\s\xa0]?"               # currency
    r"(-?[\d,]+\.?\d*)"           # amount (may be negative for refunds)
    r"尾号(\d{4})[\s\xa0]?"       # card last 4
    r"(消费|退货|还款|取现)"       # transaction type
    r"[\s\xa0]?"
    r"(.+)"                        # merchant
)

# Regex for the date header line
_DATE_RE = re.compile(r"(\d{4}/\d{2}/\d{2})[\s\xa0]?您的消费明细如下")


def parse_email(email_data):
    """Parse a CMB email and extract transactions.

    Args:
        email_data: dict with uid, subject, body_html, body_text, date

    Returns:
        dict with bill_type ('daily'/'monthly'/'unknown') and transactions list
    """
    subject = email_data.get("subject", "")
    body_html = email_data.get("body_html", "")

    if not body_html:
        return {"bill_type": "unknown", "transactions": []}

    # "每日信用管家" — the main daily digest from CMB
    if "信用管家" in subject or "消费明细" in subject or "交易提醒" in subject or "消费提醒" in subject:
        transactions = _parse_daily_digest(body_html)
        if transactions:
            return {"bill_type": "daily", "transactions": transactions}

    # Monthly statement
    if any(kw in subject for kw in ["电子账单", "对账单", "月账单", "账单提醒", "信用卡账单"]):
        transactions = _parse_monthly_statement(body_html)
        if transactions:
            return {"bill_type": "monthly", "transactions": transactions}

    # Fallback: try daily digest parsing on any CMB email
    transactions = _parse_daily_digest(body_html)
    if transactions:
        return {"bill_type": "daily", "transactions": transactions}

    return {"bill_type": "unknown", "transactions": []}


def _parse_daily_digest(body_html):
    """Parse CMB '每日信用管家' email.

    Extracts date from header line and transactions from td cells.
    Each email contains one date and multiple transactions.
    """
    soup = BeautifulSoup(body_html, "lxml")
    transactions = []
    trans_date = None

    # Collect all text from td elements
    seen = set()  # deduplicate repeated td texts (CMB nests tables)

    for td in soup.find_all("td"):
        text = td.get_text(strip=True)
        if not text or text in seen:
            continue
        seen.add(text)

        # Normalize \xa0 to space for matching, but keep original for merchant
        text_norm = text.replace("\xa0", " ")

        # Check for date header
        date_match = _DATE_RE.search(text_norm)
        if date_match:
            date_str = date_match.group(1)  # e.g. "2026/03/15"
            try:
                trans_date = datetime.strptime(date_str, "%Y/%m/%d").strftime("%Y-%m-%d")
            except ValueError:
                pass
            continue

        # Check for transaction line
        trans_match = _TRANS_RE.search(text_norm)
        if trans_match:
            time_str = trans_match.group(1)
            amount_str = trans_match.group(2)
            card_last4 = trans_match.group(3)
            trans_type = trans_match.group(4)
            merchant = trans_match.group(5).strip()

            amount = _parse_amount(amount_str)
            if amount is None:
                continue

            # For refunds (退货), amount is negative in email; store as negative
            is_refund = trans_type == "退货" or amount < 0

            transactions.append({
                "card_last4": card_last4,
                "trans_date": trans_date or datetime.now().strftime("%Y-%m-%d"),
                "post_date": trans_date or datetime.now().strftime("%Y-%m-%d"),
                "amount": abs(amount),
                "currency": "CNY",
                "merchant": merchant,
                "trans_type": trans_type,
                "is_refund": is_refund,
                "bill_type": "daily",
            })

    # Deduplicate: CMB nests tables so each transaction appears ~3 times
    # Use (card_last4, time, amount, merchant) as key
    unique = {}
    for t in transactions:
        key = (t["card_last4"], t["trans_date"], t["amount"], t["merchant"])
        if key not in unique:
            unique[key] = t

    return list(unique.values())


def _parse_monthly_statement(body_html):
    """Parse CMB monthly statement email.

    Monthly statements use HTML tables with structured columns.
    """
    soup = BeautifulSoup(body_html, "lxml")
    transactions = []
    text = soup.get_text()
    card_matches = re.findall(r"尾号(\d{4})", text)

    tables = soup.find_all("table")
    for table in tables:
        rows = table.find_all("tr")
        if len(rows) < 2:
            continue

        header_row = rows[0]
        headers = [td.get_text(strip=True) for td in header_row.find_all(["td", "th"])]
        header_text = " ".join(headers)

        if not any(kw in header_text for kw in ["交易日", "记账日", "交易说明", "摘要", "金额"]):
            continue

        col_map = _map_columns(headers)
        if not col_map:
            continue

        current_card = card_matches[0] if card_matches else "0000"

        for row in rows[1:]:
            cells = row.find_all(["td", "th"])
            cell_texts = [c.get_text(strip=True) for c in cells]
            if len(cell_texts) < max(col_map.values()) + 1:
                continue

            row_text = " ".join(cell_texts)
            card_in_row = re.search(r"尾号(\d{4})", row_text)
            if card_in_row:
                current_card = card_in_row.group(1)
                continue

            trans = _extract_row(cell_texts, col_map, current_card)
            if trans:
                transactions.append(trans)

    return transactions


def _map_columns(headers):
    """Map header names to column indices."""
    col_map = {}
    for i, h in enumerate(headers):
        h = h.strip()
        if any(kw in h for kw in ["交易日", "交易时间"]):
            col_map["trans_date"] = i
        elif "记账日" in h:
            col_map["post_date"] = i
        elif any(kw in h for kw in ["交易说明", "摘要", "交易描述", "说明"]):
            col_map["merchant"] = i
        elif any(kw in h for kw in ["金额", "交易金额", "人民币"]):
            col_map["amount"] = i
        elif "卡号" in h:
            col_map["card"] = i

    if "trans_date" not in col_map or "amount" not in col_map:
        return None
    return col_map


def _extract_row(cells, col_map, current_card):
    """Extract a single transaction from a table row."""
    try:
        trans_date = _normalize_date(cells[col_map["trans_date"]].strip())
        if not trans_date:
            return None

        post_date = None
        if "post_date" in col_map:
            post_date = _normalize_date(cells[col_map["post_date"]].strip())

        amount = _parse_amount(cells[col_map["amount"]].strip())
        if amount is None or amount <= 0:
            return None

        merchant = cells[col_map.get("merchant", -1)].strip() if "merchant" in col_map else "未知商户"

        card_last4 = current_card
        if "card" in col_map:
            m = re.search(r"(\d{4})", cells[col_map["card"]].strip())
            if m:
                card_last4 = m.group(1)

        return {
            "card_last4": card_last4,
            "trans_date": trans_date,
            "post_date": post_date or trans_date,
            "amount": amount,
            "currency": "CNY",
            "merchant": merchant,
            "bill_type": "monthly",
        }
    except (IndexError, ValueError):
        return None


def _normalize_date(date_str):
    """Normalize various date formats to YYYY-MM-DD."""
    if not date_str:
        return None
    date_str = date_str.strip()
    for fmt in ["%Y-%m-%d", "%Y/%m/%d", "%Y年%m月%d日", "%m/%d", "%m-%d"]:
        try:
            dt = datetime.strptime(date_str, fmt)
            if dt.year == 1900:
                dt = dt.replace(year=datetime.now().year)
            return dt.strftime("%Y-%m-%d")
        except ValueError:
            continue
    return None


def _parse_amount(amount_str):
    """Parse amount string to float. Returns None for unparseable strings."""
    if not amount_str:
        return None
    try:
        cleaned = re.sub(r"[¥￥$,\s\xa0元]", "", amount_str)
        return float(cleaned)
    except ValueError:
        return None
