"""Category mapper — maps merchant names to spending categories.

Generated by claude-internal tools.
"""
from models.database import get_db


def categorize_merchant(merchant):
    """Map a merchant name to a spending category.

    First checks the category_rules table (ordered by priority desc),
    then falls back to '其他'.
    """
    if not merchant:
        return "其他"

    db = get_db()
    try:
        rules = db.execute(
            "SELECT pattern, category FROM category_rules ORDER BY priority DESC"
        ).fetchall()

        merchant_lower = merchant.lower()
        for rule in rules:
            if rule["pattern"].lower() in merchant_lower:
                return rule["category"]
    finally:
        db.close()

    return "其他"
