"""Deduplication logic — prevents duplicate transactions from daily/monthly overlap.

Generated by claude-internal tools.
"""
import hashlib


def compute_dedup_hash(card_last4, trans_date, amount, merchant):
    """Compute SHA-256 hash for transaction deduplication.

    Uses card_last4 + date + amount + merchant to identify unique transactions.
    """
    raw = f"{card_last4}|{trans_date}|{amount:.2f}|{merchant}"
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def is_duplicate(db, dedup_hash):
    """Check if a transaction with this hash already exists."""
    row = db.execute(
        "SELECT id FROM transactions WHERE dedup_hash = ?", (dedup_hash,)
    ).fetchone()
    return row is not None
