"""Email fetcher service — connects to 163 IMAP and downloads CMB bill emails.

Generated by claude-internal tools.
"""
import imaplib
import email
from email.header import decode_header
from datetime import datetime, timedelta
import re
import config
from models.database import get_db


def _decode_header_value(value):
    """Decode an email header value."""
    if value is None:
        return ""
    decoded_parts = decode_header(value)
    result = []
    for part, charset in decoded_parts:
        if isinstance(part, bytes):
            result.append(part.decode(charset or "utf-8", errors="replace"))
        else:
            result.append(part)
    return "".join(result)


def connect_imap():
    """Connect to 163 IMAP with ID command (required by 163)."""
    mail = imaplib.IMAP4_SSL(config.IMAP_HOST, config.IMAP_PORT)

    # Register ID command (not in Python's imaplib by default)
    imaplib.Commands["ID"] = ("NONAUTH", "AUTH", "SELECTED")

    # 163 requires ID command before login, otherwise returns password error
    mail._simple_command(
        "ID",
        '("name" "cmb-bill-tracker" "version" "1.0.0" "vendor" "cmb-bill-tracker")',
    )

    mail.login(config.EMAIL_ADDRESS, config.EMAIL_AUTH_CODE)
    return mail


def search_emails(mail, date_from, date_to):
    """Search for CMB bill emails in date range.

    Args:
        mail: IMAP connection
        date_from: datetime object
        date_to: datetime object

    Returns:
        list of email UIDs
    """
    mail.select("INBOX")

    # IMAP date format
    since_str = date_from.strftime("%d-%b-%Y")
    before_str = (date_to + timedelta(days=1)).strftime("%d-%b-%Y")

    # Search by date range
    search_criteria = f'(SINCE "{since_str}" BEFORE "{before_str}")'
    status, data = mail.uid("search", None, search_criteria)

    if status != "OK":
        return []

    all_uids = data[0].split()
    if not all_uids:
        return []

    # Filter for CMB related emails by fetching headers
    cmb_uids = []
    # Process in batches to avoid timeout
    batch_size = 50
    for i in range(0, len(all_uids), batch_size):
        batch = all_uids[i : i + batch_size]
        uid_list = b",".join(batch)
        status, header_data = mail.uid(
            "fetch", uid_list, "(BODY.PEEK[HEADER.FIELDS (FROM SUBJECT)])"
        )
        if status != "OK":
            continue

        current_uid = None
        for item in header_data:
            if isinstance(item, tuple):
                # Extract UID from response
                uid_match = re.search(rb"UID (\d+)", item[0])
                if uid_match:
                    current_uid = uid_match.group(1)

                header_text = item[1].decode("utf-8", errors="replace")
                # Check if it's from CMB (招商银行)
                if _is_cmb_email(header_text):
                    cmb_uids.append(current_uid)

    return cmb_uids


def _is_cmb_email(header_text):
    """Check if email header indicates a CMB bill email."""
    header_lower = header_text.lower()
    cmb_indicators = [
        "招商银行",
        "cmbchina",
        "cmb",
        "95555",
        "信用卡",
    ]
    return any(indicator in header_lower or indicator in header_text for indicator in cmb_indicators)


def fetch_email(mail, uid):
    """Fetch a single email by UID.

    Returns:
        dict with uid, subject, from_addr, date, body_html, body_text
    """
    status, data = mail.uid("fetch", uid, "(RFC822)")
    if status != "OK":
        return None

    raw_email = data[0][1]
    msg = email.message_from_bytes(raw_email)

    subject = _decode_header_value(msg.get("Subject", ""))
    from_addr = _decode_header_value(msg.get("From", ""))
    date_str = msg.get("Date", "")

    # Extract HTML and text body
    body_html = ""
    body_text = ""
    if msg.is_multipart():
        for part in msg.walk():
            content_type = part.get_content_type()
            if content_type == "text/html":
                payload = part.get_payload(decode=True)
                charset = part.get_content_charset() or "utf-8"
                body_html = payload.decode(charset, errors="replace")
            elif content_type == "text/plain":
                payload = part.get_payload(decode=True)
                charset = part.get_content_charset() or "utf-8"
                body_text = payload.decode(charset, errors="replace")
    else:
        content_type = msg.get_content_type()
        payload = msg.get_payload(decode=True)
        charset = msg.get_content_charset() or "utf-8"
        if content_type == "text/html":
            body_html = payload.decode(charset, errors="replace")
        else:
            body_text = payload.decode(charset, errors="replace")

    uid_str = uid.decode() if isinstance(uid, bytes) else str(uid)

    return {
        "uid": uid_str,
        "subject": subject,
        "from_addr": from_addr,
        "date": date_str,
        "body_html": body_html,
        "body_text": body_text,
    }


def is_email_processed(uid_str):
    """Check if an email UID has already been processed."""
    db = get_db()
    row = db.execute(
        "SELECT id FROM email_logs WHERE email_uid = ? AND parsed_status = 'success'",
        (uid_str,),
    ).fetchone()
    db.close()
    return row is not None


def fetch_cmb_emails(date_from, date_to, fetch_log_id=None):
    """Main entry: fetch CMB emails in date range.

    Args:
        date_from: datetime
        date_to: datetime
        fetch_log_id: optional fetch_logs.id for progress tracking

    Returns:
        list of email dicts (uid, subject, from_addr, date, body_html, body_text)
    """
    db = get_db()
    mail = None
    emails = []

    try:
        mail = connect_imap()
        uids = search_emails(mail, date_from, date_to)

        if fetch_log_id:
            db.execute(
                "UPDATE fetch_logs SET emails_found = ? WHERE id = ?",
                (len(uids), fetch_log_id),
            )
            db.commit()

        for uid in uids:
            uid_str = uid.decode() if isinstance(uid, bytes) else str(uid)
            if is_email_processed(uid_str):
                continue

            email_data = fetch_email(mail, uid)
            if email_data:
                emails.append(email_data)

    finally:
        if mail:
            try:
                mail.logout()
            except Exception:
                pass
        db.close()

    return emails
