"""Full pipeline: fetch emails → parse → dedup → insert into DB.

Generated by claude-internal tools.
"""
from datetime import datetime
from models.database import get_db
from services.email_fetcher import fetch_cmb_emails
from services.bill_parser import parse_email
from services.dedup import compute_dedup_hash, is_duplicate
from services.category_mapper import categorize_merchant


def _mark_refund(db, refund_trans):
    """Find the original transaction matching this refund and mark it as refunded."""
    row = db.execute(
        """SELECT id FROM transactions
           WHERE card_last4 = ? AND merchant = ? AND amount = ?
                 AND refunded = 0 AND trans_date <= ?
           ORDER BY trans_date DESC
           LIMIT 1""",
        (
            refund_trans["card_last4"],
            refund_trans["merchant"],
            refund_trans["amount"],
            refund_trans["trans_date"],
        ),
    ).fetchone()

    if row:
        db.execute(
            "UPDATE transactions SET refunded = 1, refund_date = ? WHERE id = ?",
            (refund_trans["trans_date"], row["id"]),
        )
        db.commit()


def run_fetch_pipeline(date_from, date_to, fetch_type="manual"):
    """Run the full fetch-parse-insert pipeline.

    Args:
        date_from: datetime
        date_to: datetime
        fetch_type: 'manual', 'daily', 'init_7d', 'init_30d', etc.

    Returns:
        fetch_log_id for status tracking
    """
    db = get_db()

    # Create fetch log
    db.execute(
        "INSERT INTO fetch_logs (fetch_type, date_from, date_to, status) VALUES (?, ?, ?, 'running')",
        (fetch_type, date_from.strftime("%Y-%m-%d"), date_to.strftime("%Y-%m-%d")),
    )
    db.commit()
    fetch_log_id = db.execute("SELECT last_insert_rowid()").fetchone()[0]
    db.close()

    # Run pipeline in current thread (for simplicity; could be threaded)
    try:
        _execute_pipeline(fetch_log_id, date_from, date_to)
    except Exception as e:
        db = get_db()
        db.execute(
            "UPDATE fetch_logs SET status = 'failed', error_message = ?, completed_at = datetime('now', 'localtime') WHERE id = ?",
            (str(e), fetch_log_id),
        )
        db.commit()
        db.close()

    return fetch_log_id


def _execute_pipeline(fetch_log_id, date_from, date_to):
    """Execute the actual pipeline."""
    db = get_db()
    emails_parsed = 0
    records_created = 0

    try:
        # Step 1: Fetch emails
        emails = fetch_cmb_emails(date_from, date_to, fetch_log_id)

        db.execute(
            "UPDATE fetch_logs SET emails_found = ? WHERE id = ?",
            (len(emails), fetch_log_id),
        )
        db.commit()

        # Step 2: Parse each email
        for email_data in emails:
            uid = email_data["uid"]

            # Log the email
            db.execute(
                """INSERT OR IGNORE INTO email_logs (email_uid, subject, from_addr, date, parsed_status)
                   VALUES (?, ?, ?, ?, 'pending')""",
                (uid, email_data["subject"], email_data["from_addr"], email_data["date"]),
            )
            db.commit()

            try:
                result = parse_email(email_data)
                bill_type = result["bill_type"]
                transactions = result["transactions"]

                if bill_type == "unknown" or not transactions:
                    db.execute(
                        "UPDATE email_logs SET parsed_status = 'skipped', bill_type = ? WHERE email_uid = ?",
                        (bill_type, uid),
                    )
                    db.commit()
                    continue

                # Step 3: Dedup and insert transactions
                email_records = 0
                for trans in transactions:
                    # Handle refunds: find and mark original transaction
                    if trans.get("is_refund"):
                        _mark_refund(db, trans)
                        continue

                    dedup_hash = compute_dedup_hash(
                        trans["card_last4"],
                        trans["trans_date"],
                        trans["amount"],
                        trans["merchant"],
                    )

                    if is_duplicate(db, dedup_hash):
                        continue

                    category = categorize_merchant(trans["merchant"])

                    db.execute(
                        """INSERT INTO transactions
                           (card_last4, trans_date, post_date, amount, currency, merchant,
                            category, bill_type, dedup_hash, email_uid)
                           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                        (
                            trans["card_last4"],
                            trans["trans_date"],
                            trans.get("post_date", trans["trans_date"]),
                            trans["amount"],
                            trans.get("currency", "CNY"),
                            trans["merchant"],
                            category,
                            trans["bill_type"],
                            dedup_hash,
                            uid,
                        ),
                    )
                    email_records += 1
                    records_created += 1

                db.execute(
                    """UPDATE email_logs
                       SET parsed_status = 'success', bill_type = ?, records_count = ?
                       WHERE email_uid = ?""",
                    (bill_type, email_records, uid),
                )
                db.commit()
                emails_parsed += 1

            except Exception as e:
                db.execute(
                    "UPDATE email_logs SET parsed_status = 'failed', error_message = ? WHERE email_uid = ?",
                    (str(e), uid),
                )
                db.commit()

        # Update fetch log
        db.execute(
            """UPDATE fetch_logs
               SET status = 'completed', emails_parsed = ?, records_created = ?,
                   completed_at = datetime('now', 'localtime')
               WHERE id = ?""",
            (emails_parsed, records_created, fetch_log_id),
        )
        db.commit()

    except Exception as e:
        db.execute(
            """UPDATE fetch_logs
               SET status = 'failed', error_message = ?,
                   completed_at = datetime('now', 'localtime')
               WHERE id = ?""",
            (str(e), fetch_log_id),
        )
        db.commit()
        raise
    finally:
        db.close()
