"""SQLite database initialization and connection management.

Generated by claude-internal tools.
"""
import sqlite3
import config


def get_db():
    """Get a database connection with row factory."""
    conn = sqlite3.connect(config.DATABASE_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


def init_db():
    """Initialize database tables."""
    conn = get_db()
    cursor = conn.cursor()

    cursor.executescript("""
        CREATE TABLE IF NOT EXISTS transactions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            card_last4 TEXT NOT NULL,
            trans_date TEXT NOT NULL,
            post_date TEXT,
            amount REAL NOT NULL,
            currency TEXT DEFAULT 'CNY',
            merchant TEXT NOT NULL,
            category TEXT DEFAULT '其他',
            bill_type TEXT NOT NULL CHECK(bill_type IN ('daily', 'monthly')),
            refunded INTEGER DEFAULT 0,
            refund_date TEXT,
            dedup_hash TEXT UNIQUE NOT NULL,
            email_uid TEXT,
            created_at TEXT DEFAULT (datetime('now', 'localtime'))
        );

        CREATE INDEX IF NOT EXISTS idx_trans_date ON transactions(trans_date);
        CREATE INDEX IF NOT EXISTS idx_card_last4 ON transactions(card_last4);
        CREATE INDEX IF NOT EXISTS idx_category ON transactions(category);
        CREATE INDEX IF NOT EXISTS idx_dedup_hash ON transactions(dedup_hash);

        CREATE TABLE IF NOT EXISTS email_logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            email_uid TEXT UNIQUE NOT NULL,
            subject TEXT,
            from_addr TEXT,
            date TEXT,
            bill_type TEXT,
            parsed_status TEXT DEFAULT 'pending' CHECK(parsed_status IN ('pending', 'success', 'failed', 'skipped')),
            records_count INTEGER DEFAULT 0,
            error_message TEXT,
            created_at TEXT DEFAULT (datetime('now', 'localtime'))
        );

        CREATE TABLE IF NOT EXISTS fetch_logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            fetch_type TEXT NOT NULL,
            date_from TEXT,
            date_to TEXT,
            status TEXT DEFAULT 'running' CHECK(status IN ('running', 'completed', 'failed')),
            emails_found INTEGER DEFAULT 0,
            emails_parsed INTEGER DEFAULT 0,
            records_created INTEGER DEFAULT 0,
            error_message TEXT,
            started_at TEXT DEFAULT (datetime('now', 'localtime')),
            completed_at TEXT
        );

        CREATE TABLE IF NOT EXISTS category_rules (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            pattern TEXT NOT NULL,
            category TEXT NOT NULL,
            priority INTEGER DEFAULT 0
        );
    """)

    # Insert default category rules if empty
    cursor.execute("SELECT COUNT(*) FROM category_rules")
    if cursor.fetchone()[0] == 0:
        default_rules = [
            # 餐饮
            ("美团", "餐饮", 10),
            ("饿了么", "餐饮", 10),
            ("麦当劳", "餐饮", 10),
            ("肯德基", "餐饮", 10),
            ("星巴克", "餐饮", 10),
            ("瑞幸", "餐饮", 10),
            ("海底捞", "餐饮", 10),
            ("餐饮", "餐饮", 5),
            ("餐厅", "餐饮", 5),
            ("食品", "餐饮", 5),
            ("咖啡", "餐饮", 5),
            ("奶茶", "餐饮", 5),
            ("面包", "餐饮", 5),
            ("烘焙", "餐饮", 5),
            # 交通
            ("滴滴", "交通", 10),
            ("高德", "交通", 10),
            ("铁路", "交通", 10),
            ("航空", "交通", 10),
            ("加油", "交通", 10),
            ("停车", "交通", 10),
            ("地铁", "交通", 10),
            ("出行", "交通", 5),
            ("打车", "交通", 5),
            ("租车", "交通", 5),
            # 网购
            ("淘宝", "网购", 10),
            ("天猫", "网购", 10),
            ("京东", "网购", 10),
            ("拼多多", "网购", 10),
            ("AMAZON", "网购", 10),
            ("亚马逊", "网购", 10),
            # 超市/日用
            ("超市", "超市/日用", 10),
            ("沃尔玛", "超市/日用", 10),
            ("家乐福", "超市/日用", 10),
            ("盒马", "超市/日用", 10),
            ("便利店", "超市/日用", 5),
            ("711", "超市/日用", 5),
            ("全家", "超市/日用", 5),
            # 娱乐
            ("电影", "娱乐", 10),
            ("游戏", "娱乐", 10),
            ("爱奇艺", "娱乐", 10),
            ("腾讯视频", "娱乐", 10),
            ("网易云", "娱乐", 10),
            ("Spotify", "娱乐", 10),
            ("Netflix", "娱乐", 10),
            # 医疗
            ("药房", "医疗", 10),
            ("医院", "医疗", 10),
            ("诊所", "医疗", 10),
            ("药店", "医疗", 10),
            # 教育
            ("书店", "教育", 10),
            ("教育", "教育", 10),
            ("培训", "教育", 5),
            # 通讯
            ("移动", "通讯", 5),
            ("联通", "通讯", 5),
            ("电信", "通讯", 5),
            ("话费", "通讯", 10),
            # 订阅/会员
            ("Apple", "订阅/会员", 5),
            ("iCloud", "订阅/会员", 10),
            ("会员", "订阅/会员", 5),
        ]
        cursor.executemany(
            "INSERT INTO category_rules (pattern, category, priority) VALUES (?, ?, ?)",
            default_rules,
        )

    conn.commit()

    # Migration: add refunded columns if missing (for existing DBs)
    cols = [r[1] for r in conn.execute("PRAGMA table_info(transactions)").fetchall()]
    if "refunded" not in cols:
        conn.execute("ALTER TABLE transactions ADD COLUMN refunded INTEGER DEFAULT 0")
        conn.execute("ALTER TABLE transactions ADD COLUMN refund_date TEXT")
        conn.commit()

    conn.close()
    print("Database initialized successfully.")


if __name__ == "__main__":
    init_db()
